import { Cliente, Artigo, Documento, Fornecedor, MovimentoStock, ConfiguracaoEmpresa } from "./types";
import { addDays, subDays } from "date-fns";

/**
 * ============================================================================
 * DADOS MOCKADOS PARA KIMA FINANCEIRO (SISTEMA DE FATURAÇÃO EM ANGOLA)
 * ============================================================================
 * Este ficheiro contém todos os dados fictícios (mockados) do sistema.
 * 
 * PARA ELIMINAR / REMOVER TODOS OS DADOS MOCKADOS:
 * 1. Pode usar o botão "Limpar Dados Mock" no cabeçalho ou nas configurações da app.
 * 2. Ou chamar a função `clearMockDataFromStorage()` importada deste ficheiro.
 * 3. Ou eliminar/comentar este ficheiro e a sua chamada em `store.ts`.
 * ============================================================================
 */

export const MOCK_EMPRESA: ConfiguracaoEmpresa = {
  id: "empresa-001",
  nomeEmpresa: "Kima Tecnologias & Serviços, Lda",
  nif: "5417082910",
  morada: "Avenida 4 de Fevereiro, Nº 102, Edifício Marginal, 4º Andar, Luanda",
  telefone: "+244 923 000 111",
  email: "contacto@kima.co.ao",
  website: "www.kima.co.ao",
  contaBancaria: "AO06 0040 0000 1234 5678 1019 1",
  banco: "Banco BAI",
  diasVencimentoPadrao: 30,
  seriesPorTipo: [
    { serie: "A", tipoDocumento: "Fatura", proximoNumero: 6, ultimoNumeroUtilizado: 5 },
    { serie: "A", tipoDocumento: "FaturaRecibo", proximoNumero: 2, ultimoNumeroUtilizado: 1 },
    { serie: "A", tipoDocumento: "Simplificada", proximoNumero: 2, ultimoNumeroUtilizado: 1 },
    { serie: "A", tipoDocumento: "Orcamento", proximoNumero: 2, ultimoNumeroUtilizado: 1 },
  ],
  inscricaoSocial: "IS-2024-8891",
  nifRegional: "LU-01",
  criadoEm: subDays(new Date(), 180),
  ultimaAtualizacao: subDays(new Date(), 5),
};

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "client-001",
    nome: "Sonangol Distribuidora S.A.",
    tipo: "PJ",
    nif: "5401239871",
    morada: "Rua Rainha Ginga, Edifício Sede, Luanda",
    telefone: "+244 911 234 567",
    email: "compras@sonangol-dist.co.ao",
    responsavel: "João Silva",
    inscricaoSocial: "IS-2024-001",
    dataCriacao: subDays(new Date(), 90),
    ultimaAtualizacao: subDays(new Date(), 10),
    ativo: true,
  },
  {
    id: "client-002",
    nome: "Construções Kwanza & Filhos Lda",
    tipo: "PJ",
    nif: "5419876542",
    morada: "Av. Dezembristas 456, Viana, Luanda",
    telefone: "+244 922 345 678",
    email: "gerencia@construcoes-kwanza.ao",
    responsavel: "Maria Santos",
    inscricaoSocial: "IS-2024-002",
    dataCriacao: subDays(new Date(), 60),
    ultimaAtualizacao: subDays(new Date(), 30),
    ativo: true,
  },
  {
    id: "client-003",
    nome: "Comércio Agro-Alimentar de Caxito",
    tipo: "PJ",
    nif: "5404567893",
    morada: "Rua da República 789, Caxito, Bengo",
    telefone: "+244 933 456 789",
    email: "comercio@agroalimentar.co.ao",
    responsavel: "Carlos Maia",
    inscricaoSocial: "IS-2024-003",
    dataCriacao: subDays(new Date(), 45),
    ultimaAtualizacao: subDays(new Date(), 15),
    ativo: true,
  },
  {
    id: "client-004",
    nome: "Pedro Manuel da Silva",
    tipo: "PF",
    nif: "006543210LA045",
    morada: "Rua 1º de Maio, Bairro Cassenda, Luanda",
    telefone: "+244 944 567 890",
    email: "pedro.silva@gmail.com",
    dataCriacao: subDays(new Date(), 20),
    ultimaAtualizacao: subDays(new Date(), 5),
    ativo: true,
  },
  {
    id: "client-005",
    nome: "Consultoria Financeira de Talatona",
    tipo: "PJ",
    nif: "5417891236",
    morada: "Via AL4, Complexo Belas Business Park, Talatona",
    telefone: "+244 955 678 901",
    email: "contacto@consultoria-talatona.ao",
    responsavel: "Filipa Nunes",
    inscricaoSocial: "IS-2024-005",
    dataCriacao: subDays(new Date(), 120),
    ultimaAtualizacao: subDays(new Date(), 2),
    ativo: true,
  },
];

export const MOCK_FORNECEDORES: Fornecedor[] = [
  {
    id: "forn-001",
    nome: "Cimentos de Angola, S.A.",
    nif: "5401112223",
    morada: "Km 20, Estrada do Kikolo, Luanda",
    telefone: "+244 912 345 678",
    email: "vendas@cimentosangola.co.ao",
    bancaria: "AO06 0040 0000 9988 7766 1012 3",
    dataCriacao: subDays(new Date(), 120),
    ultimaAtualizacao: subDays(new Date(), 20),
    ativo: true,
  },
  {
    id: "forn-002",
    nome: "Aços & Metais de Viana, Lda",
    nif: "5404445556",
    morada: "Polo Industrial de Viana, Luanda",
    telefone: "+244 923 456 789",
    email: "comercial@acosmetais.co.ao",
    bancaria: "AO06 0006 0000 1122 3344 1015 6",
    dataCriacao: subDays(new Date(), 100),
    ultimaAtualizacao: subDays(new Date(), 15),
    ativo: true,
  },
  {
    id: "forn-003",
    nome: "Distribuidora Alimentar Central",
    nif: "5407778889",
    morada: "Zona Franca do Porto de Luanda",
    telefone: "+244 934 567 890",
    email: "pedidos@alimentoscentral.co.ao",
    bancaria: "AO06 0055 0000 4455 6677 1018 9",
    dataCriacao: subDays(new Date(), 90),
    ultimaAtualizacao: subDays(new Date(), 10),
    ativo: true,
  },
];

export const MOCK_ARTIGOS: Artigo[] = [
  {
    id: "artigo-001",
    codigo: "CONS-001",
    descricao: "Consultoria Financeira e Gestão",
    categoria: "Serviços",
    unidadeMedida: "H",
    preco: 25000,
    taxaIVA: 14,
    stock: 100,
    stockMinimo: 10,
    dataCriacao: subDays(new Date(), 60),
    ultimaAtualizacao: subDays(new Date(), 10),
    ativo: true,
  },
  {
    id: "artigo-002",
    codigo: "AUDIT-001",
    descricao: "Auditoria Contabilística e Fiscal",
    categoria: "Serviços",
    unidadeMedida: "H",
    preco: 30000,
    taxaIVA: 14,
    stock: 150,
    stockMinimo: 20,
    dataCriacao: subDays(new Date(), 50),
    ultimaAtualizacao: subDays(new Date(), 8),
    ativo: true,
  },
  {
    id: "artigo-003",
    codigo: "TRIB-001",
    descricao: "Formação em Conformidade Fiscal e SAF-T",
    categoria: "Serviços",
    unidadeMedida: "H",
    preco: 20000,
    taxaIVA: 14,
    stock: 80,
    stockMinimo: 15,
    dataCriacao: subDays(new Date(), 45),
    ultimaAtualizacao: subDays(new Date(), 5),
    ativo: true,
  },
  {
    id: "artigo-004",
    codigo: "MAT-001",
    descricao: "Saco de Cimento Portland 50kg",
    categoria: "Materiais de Construção",
    unidadeMedida: "UN",
    preco: 4800,
    taxaIVA: 7,
    stock: 450,
    stockMinimo: 100,
    fornecedorId: "forn-001",
    dataCriacao: subDays(new Date(), 40),
    ultimaAtualizacao: subDays(new Date(), 3),
    ativo: true,
  },
  {
    id: "artigo-005",
    codigo: "MAT-002",
    descricao: "Aço Varão Nervurado 12mm",
    categoria: "Materiais de Construção",
    unidadeMedida: "KG",
    preco: 650,
    taxaIVA: 7,
    stock: 1800,
    stockMinimo: 200,
    fornecedorId: "forn-002",
    dataCriacao: subDays(new Date(), 38),
    ultimaAtualizacao: subDays(new Date(), 4),
    ativo: true,
  },
  {
    id: "artigo-006",
    codigo: "ALI-001",
    descricao: "Saco de Arroz Agulha 25kg",
    categoria: "Alimentação",
    unidadeMedida: "UN",
    preco: 14500,
    taxaIVA: 0,
    stock: 130,
    stockMinimo: 30,
    fornecedorId: "forn-003",
    dataCriacao: subDays(new Date(), 35),
    ultimaAtualizacao: subDays(new Date(), 2),
    ativo: true,
  },
  {
    id: "artigo-007",
    codigo: "ALI-002",
    descricao: "Caixa de Óleo Alimentar 12x1L",
    categoria: "Alimentação",
    unidadeMedida: "UN",
    preco: 18000,
    taxaIVA: 0,
    stock: 280,
    stockMinimo: 50,
    fornecedorId: "forn-003",
    dataCriacao: subDays(new Date(), 33),
    ultimaAtualizacao: subDays(new Date(), 1),
    ativo: true,
  },
  {
    id: "artigo-008",
    codigo: "SOFT-001",
    descricao: "Licença Anual Kima Facturação Web",
    categoria: "Software",
    unidadeMedida: "UN",
    preco: 120000,
    taxaIVA: 14,
    stock: 99,
    stockMinimo: 5,
    dataCriacao: subDays(new Date(), 30),
    ultimaAtualizacao: subDays(new Date(), 1),
    ativo: true,
  },
];

export const MOCK_DOCUMENTOS: Documento[] = [
  {
    id: "doc-001",
    tipo: "Fatura",
    serie: "A",
    numero: "1",
    numeroCompleto: "A/000001",
    clienteId: "client-001",
    dataEmissao: subDays(new Date(), 30),
    dataVencimento: subDays(new Date(), 5),
    formaPagamento: "Transferência",
    status: "Pago",
    linhas: [
      {
        id: "linha-001",
        artigoId: "artigo-001",
        descricao: "Consultoria Financeira e Gestão",
        quantidade: 40,
        preco: 25000,
        taxaIVA: 14,
        total: 1000000,
        unidadeMedida: "H",
      },
      {
        id: "linha-002",
        artigoId: "artigo-008",
        descricao: "Licença Anual Kima Facturação Web",
        quantidade: 2,
        preco: 120000,
        taxaIVA: 14,
        total: 240000,
        unidadeMedida: "UN",
      },
    ],
    observacoes: "Pagamento confirmado por transferência bancária (Comprovativo BAI-8849)",
    subtotal: 1240000,
    totalIVA: 173600,
    total: 1413600,
    dataPagamento: subDays(new Date(), 10),
    criadoPor: "admin",
    atualizadoPor: "admin",
    dataAtualizacao: subDays(new Date(), 10),
  },
  {
    id: "doc-002",
    tipo: "Fatura",
    serie: "A",
    numero: "2",
    numeroCompleto: "A/000002",
    clienteId: "client-002",
    dataEmissao: subDays(new Date(), 20),
    dataVencimento: addDays(new Date(), 10),
    formaPagamento: "Transferência",
    status: "Pendente",
    linhas: [
      {
        id: "linha-003",
        artigoId: "artigo-004",
        descricao: "Saco de Cimento Portland 50kg",
        quantidade: 100,
        preco: 4800,
        taxaIVA: 7,
        total: 480000,
        unidadeMedida: "UN",
      },
      {
        id: "linha-004",
        artigoId: "artigo-005",
        descricao: "Aço Varão Nervurado 12mm",
        quantidade: 500,
        preco: 650,
        taxaIVA: 7,
        total: 325000,
        unidadeMedida: "KG",
      },
    ],
    observacoes: "Aguardando confirmação de pagamento bancário",
    subtotal: 805000,
    totalIVA: 56350,
    total: 861350,
    criadoPor: "admin",
    atualizadoPor: "admin",
    dataAtualizacao: subDays(new Date(), 20),
  },
  {
    id: "doc-003",
    tipo: "FaturaRecibo",
    serie: "A",
    numero: "1",
    numeroCompleto: "FR A/000001",
    clienteId: "client-003",
    dataEmissao: subDays(new Date(), 12),
    dataVencimento: subDays(new Date(), 12),
    formaPagamento: "Multicaixa",
    status: "Pago",
    linhas: [
      {
        id: "linha-005",
        artigoId: "artigo-006",
        descricao: "Saco de Arroz Agulha 25kg",
        quantidade: 20,
        preco: 14500,
        taxaIVA: 0,
        total: 290000,
        unidadeMedida: "UN",
      },
      {
        id: "linha-006",
        artigoId: "artigo-007",
        descricao: "Caixa de Óleo Alimentar 12x1L",
        quantidade: 15,
        preco: 18000,
        taxaIVA: 0,
        total: 270000,
        unidadeMedida: "UN",
      },
    ],
    observacoes: "Pago no TPA no ato da entrega",
    subtotal: 560000,
    totalIVA: 0,
    total: 560000,
    dataPagamento: subDays(new Date(), 12),
    criadoPor: "admin",
    atualizadoPor: "admin",
    dataAtualizacao: subDays(new Date(), 12),
  },
  {
    id: "doc-004",
    tipo: "Simplificada",
    serie: "A",
    numero: "1",
    numeroCompleto: "FS A/000001",
    clienteId: "client-004",
    dataEmissao: subDays(new Date(), 5),
    dataVencimento: addDays(new Date(), 25),
    formaPagamento: "POS",
    status: "Pendente",
    linhas: [
      {
        id: "linha-007",
        artigoId: "artigo-003",
        descricao: "Formação em Conformidade Fiscal e SAF-T",
        quantidade: 4,
        preco: 20000,
        taxaIVA: 14,
        total: 80000,
        unidadeMedida: "H",
      },
    ],
    observacoes: "Inscrição em curso de atualização fiscal",
    subtotal: 80000,
    totalIVA: 11200,
    total: 91200,
    criadoPor: "admin",
    atualizadoPor: "admin",
    dataAtualizacao: subDays(new Date(), 5),
  },
  {
    id: "doc-005",
    tipo: "Orcamento",
    serie: "A",
    numero: "1",
    numeroCompleto: "OR A/000001",
    clienteId: "client-005",
    dataEmissao: subDays(new Date(), 2),
    dataVencimento: addDays(new Date(), 28),
    formaPagamento: "Transferência",
    status: "Rascunho",
    linhas: [
      {
        id: "linha-008",
        artigoId: "artigo-002",
        descricao: "Auditoria Contabilística e Fiscal",
        quantidade: 60,
        preco: 30000,
        taxaIVA: 14,
        total: 1800000,
        unidadeMedida: "H",
      },
    ],
    observacoes: "Proposta de auditoria financeira anual válida por 30 dias",
    subtotal: 1800000,
    totalIVA: 252000,
    total: 2052000,
    criadoPor: "admin",
    atualizadoPor: "admin",
    dataAtualizacao: subDays(new Date(), 2),
  },
];

export const MOCK_MOVIMENTOS_STOCK: MovimentoStock[] = [
  {
    id: "mov-001",
    artigoId: "artigo-004",
    tipo: "Entrada",
    quantidade: 550,
    referencia: "GUIA-FORN-101",
    observacoes: "Entrada de stock de cimento via Fornecedor Cimentos de Angola",
    data: subDays(new Date(), 60),
  },
  {
    id: "mov-002",
    artigoId: "artigo-004",
    tipo: "Saída",
    quantidade: 100,
    referencia: "A/000002",
    observacoes: "Saída referente à Fatura A/000002 para Construções Kwanza",
    data: subDays(new Date(), 20),
  },
  {
    id: "mov-003",
    artigoId: "artigo-005",
    tipo: "Entrada",
    quantidade: 2300,
    referencia: "GUIA-FORN-102",
    observacoes: "Recepção de varões de aço do fornecedor Aços & Metais",
    data: subDays(new Date(), 50),
  },
  {
    id: "mov-004",
    artigoId: "artigo-005",
    tipo: "Saída",
    quantidade: 500,
    referencia: "A/000002",
    observacoes: "Saída referente à Fatura A/000002",
    data: subDays(new Date(), 20),
  },
  {
    id: "mov-005",
    artigoId: "artigo-006",
    tipo: "Entrada",
    quantidade: 150,
    referencia: "GUIA-FORN-103",
    observacoes: "Abastecimento inicial de arroz agulha",
    data: subDays(new Date(), 40),
  },
];

/**
 * Função para retornar todos os dados mockados num único objeto estruturado.
 */
export function loadMockData() {
  return {
    empresa: MOCK_EMPRESA,
    clientes: MOCK_CLIENTES,
    artigos: MOCK_ARTIGOS,
    fornecedores: MOCK_FORNECEDORES,
    documentos: MOCK_DOCUMENTOS,
    movimentosStock: MOCK_MOVIMENTOS_STOCK,
  };
}
